### ISSUE TITLE
Ideas for points not showing

### ISSUE THREAD

**Issue by prince-chrismc** [DJNGattuso/Computer_Graphics#1]
https://github.com/DJNGattuso/Computer_Graphics/blob/97c5fc76c76dea849b26720cb0db9601f2112619/Assignment2/comp371/Main.cpp#L271

for mine im using 
```c++
   const glm::vec3 center(0.0f, 0.0f, 0.0f);
   const glm::vec3 up(0.0f, 1.0f, 0.0f);
   const glm::vec3 eye(0.0f, 50.0f, -50.0f);
```

# 
https://github.com/DJNGattuso/Computer_Graphics/blob/97c5fc76c76dea849b26720cb0db9601f2112619/Assignment2/comp371/Main.cpp#L282
mine is 
```c++
glm::mat4 model_matrix = glm::scale(glm::mat4(), glm::vec3(0.05f));
```

# 
https://github.com/DJNGattuso/Computer_Graphics/blob/97c5fc76c76dea849b26720cb0db9601f2112619/Assignment2/comp371/Main.cpp#L175

so i can have a square I did this...
```c++
   int x = (0 - image.width()/2), z = (0 - image.height() / 2);
   std::vector<glm::vec3> verticies_all;

   for (CImg<float>::iterator it = image.begin(); it < image.end(); ++it)
   {
      verticies_all.emplace_back(glm::vec3(x++, *it, z));
      if(x == image.width()) {x = (0 - image.width() / 2); z += 1; }
   }
```

**Comment by DJNGattuso** [comment]
It turns out that the points were being drawn at different coordinates then where I had my camera. I'll adjust the centre and the eye so that I can see the mesh.

Thanks @prince-chrismc
